name: go-ci
on:
  pull_request:
  workflow_dispatch:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/garaj-production/*
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
#      - name: Configure git for private modules
#        env:
#          TOKEN: ${{ secrets.TEST }}
#        run: git config --global url."https://ahatojli4:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.41.1

          github-token: ${{secrets.TEST_TKN}}

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --skip-dirs ansible api configs ddl delivery-stub dockerfiles http pusher-api pusher-tests

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
